 <ol  id="leftmenuinnerinner">
 	<li><a href="python-basic">About Python</a></li>
 	<li><a href="python-identifier">Python Identifier</a>
 	<li><a href="python-keyword">Python Keyword</a></li>
 	<li><a href="python-data-types">Python Data Type</a></li>
	<li><a href="python-variable">Python Variable</a></li>
	<li><a href="python-operators">Python Operators</a></li>
	<li><a href="python-control-statements">Python Control Statements</a></li>
	<li><a href="python-array">Python Array</a></li>
	<li><a href="python-input-output">Python Input Output</a></li>
	<li><a href="python-list">Python List</a></li>
	<li><a href="python-set">Python Set</a></li>
	<li><a href="python-tuple">Python Tuple</a></li>
	<li><a href="python-dictionary">Python Dictionary</a></li>
	<li><a href="python-function">Python Function</a></li>
	<li><a href="python-numbers-format">Python Numbers Format</a></li>
	<li><a href="python-class-and-object">Python Class and Object</a></li>
	<li><a href="python-object-class">Python Object class</a></li>
	<li><a href="python-method">Python Method</a></li>
	<li><a href="python-decorators">python Decorators</a></li>
	<li><a href="python-constructor">Python Constructor</a></li>
	<li><a href="python-string">Python String</a></li>
	<li><a href="python-inheritance">Python Inheritance</a></li>
	<li><a href="python-super-keyword">python Super</a></li>
	<li><a href="python-polymorphism">Python Polymorphism</a></li>
	<li><a href="python-encapsulation">python Encapsulation</a></li>
	<li><a href="python-abstraction">Python Abstraction</a></li>
	<li><a href="python-packages-modules">python Packages and Modules</a></li>
	<li><a href="python-exception-handling">Python Exception Handling</a></li>
	<li><a href="python-regular-expressions">Python Regular Expressions</a></li>
	<li><a href="python-database-connectivity">Python Database Connectivity</a></li>
	<li><a href="python-file-handling">Python File Handling</a></li>
	<li><a href="python-networking">Python Networking</a></li>
	<li><a href="python-multithreading">Python Multithreading</a></li>
	<li><a href="python-dates">Python Dates</a></li>
	<li><a href="python-time">python_Time</a></li>
	<li><a href="python-boto3-aws">Python Boto3 AWS</a></li>
</ol> 
